modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL="https://github.com/WagYourOrg/UniConfig/issues"
license = "MPL-2.0"

[[mods]]
modId = "uniconfig_test"
version = "${version}"
displayName = "UniConfig Test"
authors = ["Wagyourtail"]
description = '''
Config test mod.
'''

[[dependencies.uniconfig_test]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2]"
ordering = "NONE"
side = "BOTH"